In [ ]:
'''
subbbb = pd.read_csv('sub_grid0.csv')

ii = df_test[df_test.grid_cell==0].index

type(ii)

subbbb.iloc[ii]

a = pd.DataFrame(columns=list('ABC'))

for i in range(800):
    a = a.append({'A': df_train[df_train.grid_cell==i].shape[0], 
                  'B': df_test[df_test.grid_cell==i].shape[0],
                  'C': df_train[df_train.grid_cell==i]['place_id'].unique().shape[0]},
                  ignore_index=True)

a.head()

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.scatter(a['A'],a['C'])

29118021.0/8607230

a.to_hdf('gridinfo.h5','table')
'''

In [57]:
# coding: utf-8
__author__ = 'Sandro Vega Pons : https://www.kaggle.com/svpons'

'''Partially based on grid_plus_classifier script:
https://www.kaggle.com/svpons/facebook-v-predicting-check-ins/grid-plus-classifier
'''

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier


def prepare_data(df, n_cell_x, n_cell_y):
    """
    Feature engineering and computation of the grid.
    """
    #Creating the grid
    size_x = 10. / n_cell_x
    size_y = 10. / n_cell_y
    eps = 0.00001  
    xs = np.where(df.x.values < eps, 0, df.x.values - eps)
    ys = np.where(df.y.values < eps, 0, df.y.values - eps)
    pos_x = (xs / size_x).astype(np.int)
    pos_y = (ys / size_y).astype(np.int)
    df['grid_cell'] = (pos_y * n_cell_x + pos_x).astype(np.int16)
    
    #Feature engineering
    fw = [500, 1000, 4, 3, 1./22., 2, 10] #feature weights (black magic here)
    df.x = df.x.values * fw[0]
    df.y = df.y.values * fw[1]
    initial_date = np.datetime64('2014-01-01T01:01', dtype='datetime64[m]') 
    d_times = pd.DatetimeIndex(initial_date + np.timedelta64(int(mn), 'm') 
                               for mn in df.time.values)    
    df['hour'] = (d_times.hour * fw[2]).astype(np.int8)
    df['weekday'] = (d_times.weekday * fw[3]).astype(np.int8)
    df['day'] = (d_times.dayofyear * fw[4]).astype(np.int8)
    df['month'] = (d_times.month * fw[5]).astype(np.int8)
    df['year'] = ((d_times.year - 2013) * fw[6]).astype(np.int8)

    df = df.drop(['time'], axis=1) 
    return df
    

def process_one_cell(df_train, df_test, grid_id, th):
    """   
    Classification inside one grid cell.
    """   
    #Working on df_train
    df_cell_train = df_train.loc[df_train.grid_cell == grid_id]
    place_counts = df_cell_train.place_id.value_counts()
    mask = (place_counts[df_cell_train.place_id.values] >= th).values
    df_cell_train = df_cell_train.loc[mask]

    #Working on df_test
    df_cell_test = df_test.loc[df_test.grid_cell == grid_id]
    row_ids = df_cell_test.index
    
    #Preparing data
    le = LabelEncoder()
    y = le.fit_transform(df_cell_train.place_id.values)
    X = df_cell_train.drop(['place_id', 'grid_cell'], axis=1).values.astype(int)
    X_test = df_cell_test.drop(['grid_cell'], axis = 1).values.astype(int)
    
    #Applying the classifier
    clf = KNeighborsClassifier(n_neighbors=25, weights='distance', 
                               metric='manhattan')
    clf.fit(X, y)
    y_pred = clf.predict_proba(X_test)
    #pred_probas = np.argsort(y_pred, axis=1)[:,::-1][:,:3]
    pred_labels = le.inverse_transform(np.argsort(y_pred, axis=1)[:,::-1][:,:3])
    
    return pred_labels, row_ids, y_pred
    
    
def process_grid(df_train, df_test, th, n_cells):
    """
    Iterates over all grid cells, aggregates the results and makes the
    submission.
    """ 
    preds = np.zeros((df_test.shape[0], 3), dtype=int)
    
    for g_id in range(1):
        if g_id % 100 == 0:
            print('iter: %s' %(g_id))
        
        #Applying classifier to one grid cell
        pred_labels, row_ids, y_pred = process_one_cell(df_train, df_test, g_id, th)

        #Updating predictions
        preds[row_ids] = pred_labels

    print('Generating submission file ...')
    #Auxiliary dataframe with the 3 best predictions for each sample
    df_aux = pd.DataFrame(preds, dtype=str, columns=['l1', 'l2', 'l3'])  
    
    #Concatenating the 3 predictions for each sample
    ds_sub = df_aux.l1.str.cat([df_aux.l2, df_aux.l3], sep=' ')
    
    #Writting to csv
    ds_sub.name = 'place_id'
    ds_sub.to_csv('sub_grid.csv', index=True, header=True, index_label='row_id') 
    
    return y_pred, pred_labels,preds
      

In [58]:
"""
"""
print('Loading data ...')
df_train = pd.read_hdf('train.h5','table')
df_test = pd.read_hdf('test.h5','table')

#Defining the size of the grid
n_cell_x = 20
n_cell_y = 40 

print('Preparing train data')
#df_train = prepare_data(df_train, n_cell_x, n_cell_y)

print('Preparing test data')
#df_test = prepare_data(df_test, n_cell_x, n_cell_y)

#Solving classification problems inside each grid cell
th = 5 #Keeping place_ids with more than th samples.   
predsss,lab,pred = process_grid(df_train, df_test, th, n_cell_x*n_cell_y)

Loading data ...
Preparing train data
Preparing test data
iter: 0
Generating submission file ...


In [59]:
predsss.shape

(11290, 322)

In [62]:
pred

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ..., 
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [54]:
lab

array([[8370753254, 9727638738, 4120068991],
       [1478305117, 5003921802, 9727638738],
       [7065354365, 3642864292, 8815983898],
       ..., 
       [7942904509, 3363064200, 7123189219],
       [2784881316, 4751915737, 3642864292],
       [8556108428, 1739846485, 1478305117]])

In [30]:
df_cell_train = df_train.loc[df_train.grid_cell == 0]
place_counts = df_cell_train.place_id.value_counts()
mask = (place_counts[df_cell_train.place_id.values] >= 5).values
df_cell_train = df_cell_train.loc[mask]

In [31]:
df_cell_train.place_id.unique().shape

(322,)

In [17]:
df_train[df_train.grid_cell==0].place_id.unique().shape

(912,)

In [34]:
np.argsort(predsss, axis=1)[:,::-1]

array([[265, 311, 108, ..., 216, 217,   0],
       [ 20, 145, 311, ..., 215, 216,   0],
       [212,  97, 284, ..., 215, 216,   0],
       ..., 
       [244,  92, 217, ..., 216, 218,   0],
       [ 71, 138,  97, ..., 217, 218,   0],
       [274,  35,  20, ..., 216, 217,   0]])

In [38]:
x = np.array([[3, 0,2], [1, 2,0], [9,2,4]])

In [39]:
x

array([[3, 0, 2],
       [1, 2, 0],
       [9, 2, 4]])

In [45]:
np.argsort(x, axis=1)

array([[1, 2, 0],
       [2, 0, 1],
       [1, 2, 0]])

In [47]:
np.sort(x,axis=1)[:,::-1]

array([[3, 2, 0],
       [2, 1, 0],
       [9, 4, 2]])

In [56]:
np.sort(predsss, axis=1)[:,::-1][:,:3]

array([[ 0.93357815,  0.06642185,  0.        ],
       [ 0.64942011,  0.13585602,  0.03774861],
       [ 0.29010672,  0.13280617,  0.1142694 ],
       ..., 
       [ 0.61415386,  0.17563176,  0.13132684],
       [ 0.49418324,  0.27696835,  0.11778962],
       [ 0.84890935,  0.08555736,  0.03276665]])

In [64]:
df_aux = pd.DataFrame(pred, columns=['l1', 'l2', 'l3']) 

In [76]:
iii = df_test.loc[df_test.grid_cell == 0].index

In [77]:
df_aux.iloc[iii]

l1          l2          l3
5        8370753254  9727638738  4120068991
442      1478305117  5003921802  9727638738
2133     7065354365  3642864292  8815983898
2794     8958485237  1376741893  6505057624
3200     5003921802  4012969260  5079685869
4345     1006316884  3027578816  4180826137
4532     1254758593  4895053921  7942904509
4758     6138829831  6505057624  8958485237
5443     6349154168  5218049605  8739476634
5991     9034650629  2477372399  8944067726
6224     8411339478  8190826815  8173555001
6449     3052798933  1231501903  5435138423
7106     8173555001  8190826815  5957043142
7271     4230167451  7540493790  8244276451
8847     7300335457  5765520742  5957043142
9151     8411339478  9034650629  2564150225
9193     6405112781  4230167451  5814859573
9908     1242364360  1557927427  4751915737
12186    8256321758  8453876154  5998323054
12495    2784881316  4751915737  3642864292
12738    6313414809  9388604588  7300335457
14102    2784881316  3642864292  5083140375
14137    4751915737  1242364360  2355254653
14346    6138829831  7555114959  8958485237
14386    7163230644  6323629255  1556214113
14454    3731899031  7123189219  7942904509
14692    4012969260  1739846485  9727638738
14749    8370753254  1739846485  8556108428
15097    5003921802  5349374802  2403464987
16797    1231501903  6349154168  4587422126
...             ...         ...         ...
8589916  5814859573  8813608705  2403464987
8590308  5445221293  3271917785  9988088517
8592226  5348440074  9034650629  8411339478
8592826  7942904509  3731899031  3363064200
8592827  4449910846  7942904509  2991457650
8593183  5765520742  7300335457  8948819147
8593972  1376741893  6138829831  1152798903
8594581  7937617850  2714209416  8556108428
8594628  4751915737  2784881316  9881561514
8595840  9388604588  7063975609  6313414809
8596015  5938943847  5765520742  3731899031
8596188  5765520742  7123189219  3731899031
8596473  7163230644  7555114959  6138829831
8596957  7163230644  7914925060  5864558238
8598757  8944067726  8173555001  8190826815
8598928  1557927427  1242364360  1895314725
8599115  3804306710  3027578816  8758023618
8599382  8556108428  8370753254  2403464987
8599576  5649281411  1254758593  5957043142
8600025  5016379997  9388604588  8944067726
8601563  5357692951  7014475222  5349374802
8601827  1006316884  2552821593  9469521476
8602102  6007444822  2148728558  4492862780
8602382  8556108428  1739846485  2403464987
8603444  7123189219  5002696932  7799745091
8604653  6126650538  3027578816  3804306710
8605309  2148728558  3642864292  4492862780
8605991  7942904509  3363064200  7123189219
8606808  2784881316  4751915737  3642864292
8606934  8556108428  1739846485  1478305117

[11290 rows x 3 columns]

In [78]:
probabi = np.zeros((df_test.shape[0], 3), dtype=float)

In [79]:
probabi[iii] = np.sort(predsss, axis=1)[:,::-1][:,:3]

In [81]:
df_aux1 = pd.DataFrame(probabi, columns=['l1', 'l2', 'l3']) 

In [82]:
df_aux1

l1        l2   l3
0        0.000000  0.000000  0.0
1        0.000000  0.000000  0.0
2        0.000000  0.000000  0.0
3        0.000000  0.000000  0.0
4        0.000000  0.000000  0.0
5        0.933578  0.066422  0.0
6        0.000000  0.000000  0.0
7        0.000000  0.000000  0.0
8        0.000000  0.000000  0.0
9        0.000000  0.000000  0.0
10       0.000000  0.000000  0.0
11       0.000000  0.000000  0.0
12       0.000000  0.000000  0.0
13       0.000000  0.000000  0.0
14       0.000000  0.000000  0.0
15       0.000000  0.000000  0.0
16       0.000000  0.000000  0.0
17       0.000000  0.000000  0.0
18       0.000000  0.000000  0.0
19       0.000000  0.000000  0.0
20       0.000000  0.000000  0.0
21       0.000000  0.000000  0.0
22       0.000000  0.000000  0.0
23       0.000000  0.000000  0.0
24       0.000000  0.000000  0.0
25       0.000000  0.000000  0.0
26       0.000000  0.000000  0.0
27       0.000000  0.000000  0.0
28       0.000000  0.000000  0.0
29       0.000000  0.000000  0.0
...           ...       ...  ...
8607200  0.000000  0.000000  0.0
8607201  0.000000  0.000000  0.0
8607202  0.000000  0.000000  0.0
8607203  0.000000  0.000000  0.0
8607204  0.000000  0.000000  0.0
8607205  0.000000  0.000000  0.0
8607206  0.000000  0.000000  0.0
8607207  0.000000  0.000000  0.0
8607208  0.000000  0.000000  0.0
8607209  0.000000  0.000000  0.0
8607210  0.000000  0.000000  0.0
8607211  0.000000  0.000000  0.0
8607212  0.000000  0.000000  0.0
8607213  0.000000  0.000000  0.0
8607214  0.000000  0.000000  0.0
8607215  0.000000  0.000000  0.0
8607216  0.000000  0.000000  0.0
8607217  0.000000  0.000000  0.0
8607218  0.000000  0.000000  0.0
8607219  0.000000  0.000000  0.0
8607220  0.000000  0.000000  0.0
8607221  0.000000  0.000000  0.0
8607222  0.000000  0.000000  0.0
8607223  0.000000  0.000000  0.0
8607224  0.000000  0.000000  0.0
8607225  0.000000  0.000000  0.0
8607226  0.000000  0.000000  0.0
8607227  0.000000  0.000000  0.0
8607228  0.000000  0.000000  0.0
8607229  0.000000  0.000000  0.0

[8607230 rows x 3 columns]

In [83]:
df_aux1.iloc[iii]

l1        l2        l3
5        0.933578  0.066422  0.000000
442      0.649420  0.135856  0.037749
2133     0.290107  0.132806  0.114269
2794     0.303156  0.196654  0.116576
3200     0.826281  0.103805  0.039152
4345     0.962505  0.037495  0.000000
4532     0.930406  0.035570  0.034024
4758     0.424146  0.224884  0.153922
5443     0.887052  0.042985  0.035574
5991     0.251025  0.224865  0.126815
6224     0.414840  0.151638  0.116447
6449     0.274114  0.153548  0.122441
7106     0.470252  0.240860  0.089753
7271     0.689097  0.072939  0.046853
8847     0.401008  0.395090  0.132431
9151     0.309197  0.119508  0.078216
9193     0.450529  0.240715  0.109113
9908     0.462013  0.199461  0.075144
12186    0.492063  0.145024  0.097067
12495    0.416121  0.325313  0.112266
12738    0.518217  0.246973  0.089413
14102    0.543731  0.218964  0.083215
14137    0.250459  0.209730  0.159956
14346    0.303095  0.158124  0.112178
14386    0.275993  0.216014  0.114499
14454    0.225537  0.150332  0.096618
14692    0.298211  0.157094  0.151558
14749    0.358663  0.212305  0.147243
15097    0.192195  0.175782  0.175523
16797    0.556637  0.301843  0.037969
...           ...       ...       ...
8589916  0.716571  0.081879  0.081161
8590308  0.958269  0.041731  0.000000
8592226  0.232223  0.191346  0.136607
8592826  0.251607  0.203137  0.192065
8592827  0.347666  0.329853  0.165281
8593183  0.729601  0.153769  0.041059
8593972  0.779562  0.113197  0.072090
8594581  0.626873  0.135962  0.067957
8594628  0.436915  0.286382  0.107604
8595840  0.521003  0.327859  0.071035
8596015  0.371642  0.191572  0.084657
8596188  0.303999  0.112045  0.081963
8596473  0.840705  0.120702  0.038593
8596957  0.346550  0.304700  0.115739
8598757  0.319362  0.220156  0.180483
8598928  0.888136  0.074576  0.037288
8599115  0.361569  0.264291  0.198726
8599382  0.707783  0.189330  0.037390
8599576  0.520763  0.367879  0.038788
8600025  0.597997  0.120049  0.071142
8601563  0.558698  0.301635  0.068762
8601827  0.432838  0.214355  0.081297
8602102  0.413125  0.249302  0.149241
8602382  0.334809  0.324947  0.140440
8603444  0.810630  0.042184  0.037965
8604653  0.261964  0.152015  0.075937
8605309  0.508200  0.226017  0.112704
8605991  0.614154  0.175632  0.131327
8606808  0.494183  0.276968  0.117790
8606934  0.848909  0.085557  0.032767

[11290 rows x 3 columns]

In [84]:
df_aux.to_hdf('grid0predictedplaces.h5','table')

In [85]:
df_aux1.to_hdf('grid0predictedprobability.h5','table')